### ISSUE TITLE
Disabling Consistency Checks

### ISSUE THREAD

**Issue by JSchimmelpfennig** [natario1/whatsapp-database-merger#11]
Hi guys,
as I'm still getting consistency errors, I'd like to disable the checks to see what is going to happend.

As mentioned [https://github.com/natario1/whatsapp-database-merger/issues/9#issuecomment-1432719716](here), one should recompile with `ignoreConsistencyChecks = true `.

But I could not finy any information where to set that option.

I tried the following:
Setting `ignoreConsistencyChecks = true` in `\src\main\kotlin\dev\natario\Table.kt`, then

```
┌──(julian㉿julian-legion)-[/mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2]
└─$ gradle build
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1, mixed mode, sharing)
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
No dependencies


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

```
┌──(julian㉿julian-legion)-[/mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2]
└─$ ./gradlew tasks
Downloading https://services.gradle.org/distributions/gradle-7.1-bin.zip
..........10%...........20%...........30%..........40%...........50%...........60%..........70%...........80%...........90%...........100%

Welcome to Gradle 7.1!

Here are the highlights of this release:
 - Faster incremental Java compilation
 - Easier source set configuration in the Kotlin DSL

For more details see https://docs.gradle.org/7.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :tasks

------------------------------------------------------------
Tasks runnable from root project 'whatsapp-database-merger'
------------------------------------------------------------

Application tasks
-----------------
run - Runs this project as a JVM application

Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildKotlinToolingMetadata - Build metadata json file containing information about the used Kotlin tooling
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes.
testClasses - Assembles test classes.

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Distribution tasks
------------------
assembleDist - Assembles the main distributions
distTar - Bundles the project as a distribution.
distZip - Bundles the project as a distribution.
installDist - Installs the project as a distribution as-is.

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'whatsapp-database-merger'.
dependencies - Displays all dependencies declared in root project 'whatsapp-database-merger'.
dependencyInsight - Displays the insight into a specific dependency in root project 'whatsapp-database-merger'.
help - Displays a help message.
javaToolchains - Displays the detected java toolchains.
kotlinDslAccessorsReport - Prints the Kotlin code for accessing the currently available project extensions and conventions.
outgoingVariants - Displays the outgoing variants of root project 'whatsapp-database-merger'.
projects - Displays the sub-projects of root project 'whatsapp-database-merger'.
properties - Displays the properties of root project 'whatsapp-database-merger'.
tasks - Displays the tasks runnable from root project 'whatsapp-database-merger'.

Verification tasks
------------------
check - Runs all checks.
test - Runs the unit tests.

Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

BUILD SUCCESSFUL in 31s
1 actionable task: 1 executed
```

```
┌──(julian㉿julian-legion)-[/mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2]
└─$ ./gradlew run --args=databases

> Task :run
[*] Input databases:
        - input/A54_msgstore.db
        - input/G8s_msgstore.db
[*] Checking consistency of input/A54_msgstore.db
        Column chat.jid_row_id is consistent! All 6570 unique entries (out of 6570) exist in the referenced table jid.
Exception in thread "main" java.lang.IllegalStateException: Database input/A54_msgstore.db is not consistent. Column chat.display_message_row_id references table message, where we expected to find a list of 983 entries, but only 979 were found.
Total count (source): 203730, total count (target): 6570
Missing=[11, 13, 15, 19]
        at dev.natario.ConsistencyKt.verifyConsistency(Consistency.kt:21)
        at dev.natario.ConsistencyKt.verifyConsistency$default(Consistency.kt:3)
        at dev.natario.MainKt.main(Main.kt:50)

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date
```

Which obviously did not work.

How can I recompile the whatsapp-database-merger with `ignoreConsistencyChecks` set to true?

Thank you :)

**Comment by natario1** [comment]
You could comment out/remove the whole body of the function in Consistency.kt file.

**Comment by JSchimmelpfennig** [comment]
Doing it like that:
```
package dev.natario

fun Database.verifyConsistency(schema: Schema, throwOnFailure: Boolean = true) {
#     schema.forEach { table ->
#         if (table.refs.isEmpty()) return@forEach
#         val columns = columns(table.name)
#         val entries = query(table.name)
#         table.refs.forEach { ref ->
#             val index = columns.indexOf(ref.name)
#             // Check that all referenced values exist in the referenced table.
#             val values: List<String> = entries.mapNotNull { it[index] }
#                 .distinct()
#                 .filterNot { it == "0" }
#             val results = count(ref.table.name, "_id in (${values.joinToString()})")
#             if (results != values.size.toLong()) {
#                 val message = "Database $this is not consistent. Column ${table}.${ref.name} references table ${ref.table}, " +
#                         "where we expected to find a list of ${values.size} entries, but only $results were found.\n" +
#                         "Total count (source): ${count(ref.table.name)}, total count (target): ${count(table.name)}\n" +
#                         "Missing=${values.toSet() - query(ref.table.name, "_id in (${values.joinToString()})").mapNotNull { it[0] }.toSet()}"
#                 if (throwOnFailure && !ref.ignoreConsistencyChecks) {
#                     error(message)
#                 } else {
#                     println("\tWarning: $message")
#                 }
#             } else {
#                 println("\tColumn ${table}.${ref.name} is consistent! All ${values.size} unique entries (out of ${entries.size}) exist in the referenced table ${ref.table}.")
#                 // println("\t\tValues=${values}")
#             }
#         }
#     }
}
```
or commenting out everything gives the following error while compiling:
```
./gradlew run --args=databases

> Task :compileKotlin FAILED
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (4, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (5, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (6, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (7, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (8, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (9, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (10, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (11, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (12, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (12, 19): Unexpected tokens (use ';' to separate expressions on the same line)
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (13, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (13, 19): Unexpected tokens (use ';' to separate expressions on the same line)
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (14, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (15, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (16, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (16, 130): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (17, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (17, 122): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (18, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (18, 123): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (19, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (20, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (21, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (22, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (23, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (24, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (25, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (26, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (27, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (28, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (29, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (30, 1): Expecting an element
e: /mnt/c/Users/admin/Downloads/whatsapp-database-merger-0.2.0b2(1)/whatsapp-database-merger-0.2.0b2/src/main/kotlin/dev/natario/Consistency.kt: (13, 32): Unresolved reference: it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
```

**Comment by natario1** [comment]
Use // instead of #.

**Comment by JSchimmelpfennig** [comment]
Oh yeah, we are in Java, I forgot that :D now it works 👍
