### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DarkXonline** [natario1/whatsapp-database-merger#2]
Can you tell me a detail instruction on how to use the tool? Especially for windows user with little knowledge.

For example, how to arrange the msgstore.db; 
eg: I want to combine mgstore (6March) and mgstore (7March), how to do it? How about the naming scheme?
naming it mgstore1.db for 7 March, and mgstore2.db for 6 March?

What command to make in cmd (windows) to combine it?
How to define output file?

Hope you can answer this ASAP as I really on my end needs here :D
Sorry for any bad English used.

**Comment by natario1** [comment]
You can name the databases however you want, as long as they end in .db. Just choose a folder , like desktop, and put the decrypted databases in `Desktop\input` subfolder. After running the tool (see README), you will find the merged database in `Desktop\output`.

**Comment by DarkXonline** [comment]
Thanks for answering, it is working now but I got errors when merging the .db

![image](https://user-images.githubusercontent.com/22949719/158047177-9dba4885-8d3c-4fe4-8e23-fd8f4f0b8a03.png)

Any fix for this one?

**Comment by natario1** [comment]
Are you able to modify the source code and rebuild the tool with `gradlew build`? If yes, I can tell you which line to modify. If not, you'll have to wait for next version

**Comment by DarkXonline** [comment]
I don't know much about modifying or building the source code, I just download the compiled binary from release page and try it out that's all :)

**Comment by SenCodeMaker** [comment]
hello having the same  issue of old db inconsistency i'm interested in creating pull request to solve this. i use to develop in java and i know a bit of gradle but i would use some guiding to update kotlin code and rebuild.

**Comment by SenCodeMaker** [comment]
here is my error i don't know if this column is softly ignorable for consistency

`[*] Checking consistency of input/msgstore.db
	Column messages_quotes.quoted_row_id is consistent! All 374 unique entries (out of 1730) exist in the referenced table messages_quotes.
	Column messages.quoted_row_id is consistent! All 1730 unique entries (out of 6470) exist in the referenced table messages_quotes.
	Column messages_vcards.message_row_id is consistent! All 0 unique entries (out of 0) exist in the referenced table messages.
	Column messages_vcards_jids.message_row_id is consistent! All 0 unique entries (out of 0) exist in the referenced table messages.
	Column messages_vcards_jids.vcard_row_id is consistent! All 0 unique entries (out of 0) exist in the referenced table messages_vcards.
	Column message_vcard_jid.message_row_id is consistent! All 0 unique entries (out of 0) exist in the referenced table messages.
	Column message_vcard_jid.vcard_jid_row_id is consistent! All 0 unique entries (out of 0) exist in the referenced table jid.
	Column group_participant_user.group_jid_row_id is consistent! All 44 unique entries (out of 996) exist in the referenced table jid.
	Column group_participant_user.user_jid_row_id is consistent! All 748 unique entries (out of 996) exist in the referenced table jid.
	Column group_participant_device.group_participant_row_id is consistent! All 996 unique entries (out of 1275) exist in the referenced table group_participant_user.
	Column group_participant_device.device_jid_row_id is consistent! All 921 unique entries (out of 1275) exist in the referenced table jid.
	Column message_forwarded.message_row_id is consistent! All 233 unique entries (out of 233) exist in the referenced table messages.
	Column messages_links.message_row_id is consistent! All 118 unique entries (out of 122) exist in the referenced table messages.
	Column audio_data.message_row_id is consistent! All 125 unique entries (out of 125) exist in the referenced table messages.
	Column user_device_info.user_jid_row_id is consistent! All 166 unique entries (out of 166) exist in the referenced table jid.
	Column chat.jid_row_id is consistent! All 137 unique entries (out of 137) exist in the referenced table jid.
	Column chat.display_message_row_id is consistent! All 87 unique entries (out of 137) exist in the referenced table messages.
	Column chat.last_message_row_id is consistent! All 87 unique entries (out of 137) exist in the referenced table messages.
	Column chat.last_read_message_row_id is consistent! All 56 unique entries (out of 137) exist in the referenced table messages.
	Column chat.last_read_receipt_sent_message_row_id is consistent! All 87 unique entries (out of 137) exist in the referenced table messages.
	Column chat.last_important_message_row_id is consistent! All 1 unique entries (out of 137) exist in the referenced table messages.
	Column chat.change_number_notified_message_row_id is consistent! All 1 unique entries (out of 137) exist in the referenced table messages.
	Column chat.last_read_ephemeral_message_row_id is consistent! All 0 unique entries (out of 137) exist in the referenced table messages.
	Column message_media.message_row_id is consistent! All 920 unique entries (out of 920) exist in the referenced table messages.
	Column message_media.chat_row_id is consistent! All 37 unique entries (out of 920) exist in the referenced table chat.
	Column receipt_user.message_row_id is consistent! All 2358 unique entries (out of 2666) exist in the referenced table messages.
	Column receipt_user.receipt_user_jid_row_id is consistent! All 133 unique entries (out of 2666) exist in the referenced table jid.
	Column receipt_device.message_row_id is consistent! All 2366 unique entries (out of 4047) exist in the referenced table messages.
	Column receipt_device.receipt_device_jid_row_id is consistent! All 151 unique entries (out of 4047) exist in the referenced table jid.
[*] Checking consistency of input/msgstore_h.db
Exception in thread "main" java.lang.IllegalStateException: Database input/msgstore_h.db is not consistent. Column messages_quotes.quoted_row_id references table messages_quotes, where we expected to find a list of 8153 entries, but only 8142 were found.
Total count (source): 36566, total count (target): 36566
Missing=[514, 15814, 18703, 19912, 21471, 21482, 21484, 21487, 21478, 28306, 30777]
	at dev.natario.ConsistencyKt.verifyConsistency(Consistency.kt:21)
	at dev.natario.ConsistencyKt.verifyConsistency$default(Consistency.kt:3)
	at dev.natario.MainKt.main(Main.kt:50)
`

**Comment by SenCodeMaker** [comment]
![image](https://user-images.githubusercontent.com/43207983/166258543-afe06440-955a-46ff-98ae-eb48f0f76716.png)

I builded another version disabling consistency checks but it gives me too large content error any thoughts ?

**Comment by natario1** [comment]
Can you identify which table and column gives you this error? By looking at previous logs.

After you identify it, you can exclude this column in the schema (add it to the list of `excludes`)

**Comment by SenCodeMaker** [comment]
ok  i can try that after, i saw only messages_quotes.message_row_id and another not so important table was concerned so i skipped consistency tests. 
 
again for the query length problem i patched with a catch in database#executeWithRows to ignore insert that don't succeed. right now it's been running for two hours. I wait and see....

**Comment by SenCodeMaker** [comment]
finally it was not able to do the job because my bases containing too much large messages and also inconsitencies maybe, it got it right directly in sql : https://github.com/SenCodeMaker/whatsapp-database-merger it much more performant also.

**Comment by durmazt** [comment]
"input databases must be already decrypted" 
I have msgstore.db.crypt14 and msgstore.db.crypt12
how to decrypt an encrypt those things?

**Comment by JSchimmelpfennig** [comment]
> "input databases must be already decrypted" I have msgstore.db.crypt14 and msgstore.db.crypt12 how to decrypt an encrypt those things?

You can use [wa-crypt-tools](https://github.com/ElDavoo/wa-crypt-tools).
